name: Build and push Docker image to GHCR

on:
  push:
    branches: [ main ]

env:
  SOLUTION_FILE: "PRN232_Presentation.sln"
  PROJECT_FOLDER: "PRN232_Presentation_API"
  IMAGE_NAME: ghcr.io/${{ github.repository_owner,, }}/prn232-demo


permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore "${{ env.SOLUTION_FILE }}"

      - name: Build
        run: dotnet build "${{ env.SOLUTION_FILE }}" --configuration Release --no-restore

      - name: Run tests (tolerant)
        run: dotnet test "${{ env.SOLUTION_FILE }}" --configuration Release --no-build --verbosity normal || echo "No tests or tests failed (non-blocking for demo)."

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: PRN232_Presentation_API
          file: PRN232_Presentation_API/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
