name: Build and Push to GHCR

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write

env:
  SOLUTION_FILE: "PRN232_Presentation.sln"
  PROJECT_FOLDER: "PRN232_Presentation_API"
  IMAGE_NAME: ghcr.io/${{ toLower(github.repository_owner) }}/prn232-demo

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore & Build
        run: |
          dotnet restore "${{ env.SOLUTION_FILE }}"
          dotnet build "${{ env.SOLUTION_FILE }}" --configuration Release --no-restore

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.PROJECT_FOLDER }}
          file: ${{ env.PROJECT_FOLDER }}/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
